"""empty message

Revision ID: 34219766a92b
Revises: 
Create Date: 2021-11-03 18:31:19.535151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34219766a92b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_cat', sa.String(length=120), nullable=True),
    sa.Column('descripcion_cat', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metodopago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_pago', sa.String(length=120), nullable=True),
    sa.Column('nombre_metpag', sa.String(length=120), nullable=True),
    sa.Column('otros_datos', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('negocios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_negocio', sa.String(length=120), nullable=False),
    sa.Column('trabajadores', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ingresos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=120), nullable=False),
    sa.Column('tipo_comprobante_ing', sa.String(length=120), nullable=False),
    sa.Column('numero_comprobante_ing', sa.String(length=120), nullable=False),
    sa.Column('fecha_ing', sa.String(length=50), nullable=False),
    sa.Column('impuesto_ing', sa.Float(), nullable=False),
    sa.Column('total_ing', sa.Float(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_comprobante', sa.String(length=120), nullable=False),
    sa.Column('numero_comprobante', sa.String(length=120), nullable=False),
    sa.Column('metodo_pago', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=False),
    sa.Column('impuesto', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detallesdeingresos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_articulo', sa.Integer(), nullable=False),
    sa.Column('cantidad_di', sa.Integer(), nullable=False),
    sa.Column('precio_di', sa.Integer(), nullable=False),
    sa.Column('ingreso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingreso_id'], ['ingresos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('codigo_barras', sa.String(length=120), nullable=True),
    sa.Column('precio_venta', sa.Float(precision=50), nullable=True),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('fecha_ingreso', sa.String(length=50), nullable=False),
    sa.Column('costo_compra', sa.Float(precision=50), nullable=False),
    sa.Column('factura_proveedor', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('detalleingreso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['detalleingreso_id'], ['detallesdeingresos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras')
    )
    op.create_table('detalledeventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalledeventas')
    op.drop_table('productos')
    op.drop_table('detallesdeingresos')
    op.drop_table('ventas')
    op.drop_table('ingresos')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('negocios')
    op.drop_table('metodopago')
    op.drop_table('categorias')
    # ### end Alembic commands ###
